# Generated by Django 3.1.7 on 2021-03-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='text',
            field=models.TextField(default='', max_length=150),
        ),
    ]
