# Generated by Django 3.1.7 on 2021-03-13 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_extras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': ['created_on'], 'ordering': ['-created_on']},
        ),
    ]
